[options]
; This is the password that allows database operations:
; admin_passwd = admin
db_host = 103.82.38.96
db_port = 5445
db_user = odoo
db_password = odoo
;addons_path = /usr/lib/python3/dist-packages/odoo/addons
default_productivity_apps = True

cors = True
cors_origins = http://103.82.38.96:4700

# cors_origins = http://localhost:4200

cors_support_credentials = True
proxy_mode = True

