[options]
; This is the password that allows database operations:
; admin_passwd = admin
db_host = False
db_port = False
db_user = odoo
db_password = False
;addons_path = /usr/lib/python3/dist-packages/odoo/addons
default_productivity_apps = True

cors = True
cors_origins = http://103.82.38.96:4700
cors_support_credentials = True
proxy_mode = 

